In [1]:
import numpy as np

In [2]:
arr_1d =np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim

1

In [5]:
arr_1d.size

4

In [6]:
# Create Two-D Array

In [7]:
arr_2d =np.array ([[1,2,3,4],
          [5,6,7,8,],
          [9,0,1,2]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


In [8]:
type(arr_2d)

numpy.ndarray

In [9]:
arr_2d.ndim

2

In [10]:
arr_2d.size

12

In [11]:
arr_2d.shape

(3, 4)

In [12]:
# (row,coloum)

In [13]:
arr_2d.dtype

dtype('int32')