In [2]:
import numpy as np

In [3]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx_1s = np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
mx_1s.dtype

dtype('int32')

In [6]:
mx_1s= np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
mx_1s = np.ones((2,4), dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]]


In [8]:
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
mx_0s = np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [11]:
mx_0s = np.zeros((4,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [13]:
em_str = ''
print(bool(em_str))

False


In [14]:
em_mx = np.empty((3,3))
print(em_mx)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23047842e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307 3.62651150e-317]]
